### ISSUE TITLE
Problem using acl....

### ISSUE THREAD

**Issue by huglester** [fuel/auth#1]
I seem not to find out how to make Auth acl to work..
My config files are locatet here: http://scrp.at/N1

While I do: 

$access = \Auth::has_access(array('users/index', array('read')));
var_dump($access); - Always get false  :(

Tried to edit auth/login/driver.php, line 152... with some print_r's:

```
public function has_access($condition, $driver = null, $entity = null)
{
    $entity = $entity ?: $this->get_user_id();
    echo "<pre>";
    if ($driver === null)
    {
        foreach (\Auth::acl(true) as $acl)
        {
            print_r($acl);
            print_r($condition);
            print_r($entity);
            if ($acl->has_access($condition, $entity))
            {
                return true;
            }
        }

        return false;
    }

    return \Auth::acl($driver)->has_access($condition, $entity);
}
```

and the result I get is:

Auth\Auth_Acl_SimpleAcl Object
(
    [id:protected] => SimpleAcl
    [config:protected] => Array
        (
            [driver] => SimpleAcl
            [id] => SimpleAcl
        )

)
Array
(
    [0] => users/index
    [1] => Array
        (
            [0] => read
        )

)
Array
(
    [0] => simplegroup
    [1] => 1
)

Shouldn't these values be different from:
[config:protected] => Array
        (
            [driver] => SimpleAcl
            [id] => SimpleAcl // I mean here probably should be some int, not string?
        )

Thank you :)

**Comment by jschreuder** [comment]
All of that looks good, there might however be a problem because of the recent casing change to the driver names (simlegroup is now SimpleGroup). I'll look into that.
