### ISSUE TITLE
[BUG] ormauth.table_columns rendered useless

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/auth#100]
**The Problem**
In classes/auth/login/ormauth.php, the _init() method states the following.

```
// deal with invalid column selections
if ($columns = \Config::get('ormauth.table_columns', array()) == array('*') or ! is_array($columns))
{
    \Config::set('ormauth.table_columns', array());
}
```

That says to load the ormauth.table_columns entry from the config, and check if that entry is the same as array('*'), then set the boolean result of the assertion to $columns. If that returns false, you check if the boolean result is an array, which will always return true, and then you clear the entry.

**Proposed Solution**
Alter the code to state the following.

```
// deal with invalid column selections
$columns = \Config::get('ormauth.table_columns', array());
if ($columns === array('*') or ! is_array($columns))
{
    \Config::set('ormauth.table_columns', array());
}
```

**Comment by WanWizard** [comment]
It need brackets, as it should do the assignment to $columns first, and compare that to `array('*')`.
