### ISSUE TITLE
[SECURITY FEATURE] Increase security by normalizing the login timing as per OWASP OTG-BUSLOGIC-004

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/auth#105]
I've been code reviewing FuelPHP, and my own code while running through the [OWASP Testing Guide](https://www.owasp.org/index.php/Test_for_Process_Timing_%28OTG-BUSLOGIC-004%29), and you've seriously impressed me with your product so far, and admittedly even taught me a few things. Nice work. However, I came across one test where a minor security improvement can be made at the expense of a little performance loss. Therefore, I suggest allowing developers to enable or disable the security feature suggested below.

**OWASP OTG-BUSLOGIC-004**
The test demonstrates how an attacker can glean information about the business logic of an application based on the response timing. While a user-base is small, the natural variances in PHP timing, and connection latency, can make an attacker unable to enumerate users in the DB through timing the response. However, as the user-base grows, the risk of timing enumeration increases.

**TESTING**
When a user logs in, \Auth::login() calls the driver's login() method. In the case of OrmAuth, it selects the row from the DB and uses the get_one() method to speed up the process by returning only the first row it finds matching the query. (LIMIT 1)

When a valid user logs in with a database consisting of thousands of accounts, The valid user may be number 100 on the list, or it could be the first row, etc. When we limit the query to pulling only the first valid row, we shave off an arbitrary amount of time to grab the user from the DB.

When an invalid account logs in, the query must run on every row until it finds that the account doesn't exist. If an attacker wishes to enumerate accounts, they could gauge the time it takes to search for an invalid account versus valid accounts.

**REMEDIATION**
Consider using get() instead of get_one() for the login and password reset queries. Add an extra configuration setting to allow for developers to turn this functionality on or off. By default it should stay off to allow for backwards compatibility.

**Comment by kenjis** [comment]
With current implementation, could you guess an account is valid or not?
And how many micro second is the difference?

How much will `get()` improve it?

**Comment by WanWizard** [comment]
I think with the unpredictable response time of your RDBMS, it will be extremely difficult to detect a valid vs a non-valid lookup. Even with a totally unloaded server, 1000 times the same query give you 1000 different response times at the micro-second level.

So I have to say I'm a lot less worried about this one. We had a similar timing issue in the past in the password validation method, where the difference was predicable. That algorithm was changed with the help of a specialized security company. They didn't have a problem with the queries at that time.

**Comment by rickmacgillis** [comment]
Alright, I'll trust your judgement. I haven't played with inflating the DB to test it out, but if it gets to be an issue at some point, I'll report it again with more detail.

**Comment by kenjis** [comment]
I think we should add account lock functionality rather than worring about very small threat like this.

**Comment by rickmacgillis** [comment]
Yep. I planned on doing that manually, but having it in the framework will help out quite a bit. Also, having the ability to force password changes, or create accounts without a password so that people can't log in until they verify their email address will be helpful. I've already built that using meta data settings, but it requires a password to be generated for the account that never gets used.

**Comment by WanWizard** [comment]
An account lookout mechanism seems useful.

The other suggestions are in my opinion application specific, and should be implemented there, not in Auth. For example, I don't agree with your validation implementation. I would create the account as normal, but at it to a group "awaiting validation", which has only limited rights. When validated by email, the group is changed to "member".

**Comment by rickmacgillis** [comment]
Oh, it does that too. New accounts are added to the banned group. When the Bit API Hub pre-launch website opens, it will have a productivity course, but people can only create accounts, not log in. As it's not on HTTPS, I only have them entering a username. They'll chose their password when we launch the main website. I forgot that that was the reason I did it that way.
