### ISSUE TITLE
Migrations do not respect connection configuration setting

### ISSUE THREAD

**Issue by jpudney** [fuel/auth#109]
Lines like [this](https://github.com/fuel/auth/blob/1.8/develop/migrations/001_auth_create_usertables.php#L21) do not respect the connection configuration that may have ben set within `Config::get('migrations.connection');`.

The use case is that a separate user may have been created with greater user privileges for creating/dropping etc of tables.

**Comment by mikepmtl** [comment]
It now fails for me in 005_auth_create_authdefaults.php
