### ISSUE TITLE
Ormauth member() fails when given a non-numeric group

### ISSUE THREAD

**Issue by Doeme** [fuel/auth#115]
Auth_Group_Ormgroup::member fails when I give it a group-object(as opposed to a group-id) when using PHP-5.6.26 and Fuel-1.8

What I'm trying to do:

```
$g=\Model\Auth_Group::find('first', array('where' => array('name' => 'Administrators')));
Auth::login('admin','admin');
Auth::member($g);
```

And admin is in the Administrators-group with ID 5.

The offending line is https://github.com/fuel/auth/blob/1.9/develop/classes/auth/group/ormgroup.php#L95 and, more precisely, the comparison `$group_id === (int) $group[1]->id`, which issues:
- True on `Auth::member(5);` (The right answer);
- False on `Auth::member($g);`
- False on `Auth::member($g->id);`
- True on `Auth::member((int) $g->id);`

Addendum: If I add an (int) cast to https://github.com/fuel/auth/blob/1.9/develop/classes/auth/group/ormgroup.php#L68, changing it to:

```
            $group_id = (int) $group_id->id;
```

The problem disappears.

**Comment by WanWizard** [comment]
It will also be
- False on `Auth::member("100");`

so your solution isn't optimal. See my comments on the PR.

**Comment by WanWizard** [comment]
PR merged.
