### ISSUE TITLE
Add reset_password() method for forgotten passwords

### ISSUE THREAD

**Issue by jschreuder** [fuel/auth#13]
UDPATED October 6, 2011.

Used to be: Unfinished forgotten_password() method in SimpleAuth driver

**Comment by nerdsrescueme** [comment]
Perhaps this can be tabled until the Email class is finished? Or just remove it for now?

**Comment by jschreuder** [comment]
Haven't decided, but v1.0 final shouldn't have an unfinished method in it. Changes are it'll be removed for v1.0. This issue is here as a reminder for me.

**Comment by jschreuder** [comment]
Removed for now.

**Comment by dhrrgn** [comment]
This should probably go back in, but be very very simple.  All it should do it return the forgotten password token, and verify a forgotten password token...that is all.  Leave the emailing and such up to the developer.  We already make them create the login forms and such themselves, so a forgotten password action or 2 is no biggie for them.

**Comment by jschreuder** [comment]
Maybe a `regenerate_password()` method that generates a random password and returns it instead? Let the way this is handled be up to the dev?

**Comment by dlpetrie** [comment]
I have a simple forgot password function that returns the random password as jschreuder mentioned for a driver I use.  I modified it to work for simpleauth - though I haven't tested it.  I put the code here ( http://scrp.at/aib ) if you wanted to take a look, it's very basic.

**Comment by jschreuder** [comment]
@dlpetrie Basicly it's good. But I think this shouldn't be called `forgotten_password()` as that implies that it is a drop-in forgotten password function, which it is not as any random person with the user/email of a user could reset that user's password. That is also the reason why I wouldn't want this method to default to a post value, the developer should call this after having done his due dillegence when it comes to such security concerns. Defaulting to a post value gives the wrong signal and is thus bad practice.

Also your last few lines can be summerized as follows: `return $affected_rows > 0 ? $password : false;`
