### ISSUE TITLE
Possible Session Fixation Vulnerability

### ISSUE THREAD

**Issue by joshuarubin** [fuel/auth#24]
After a user successfully logs in, the session id should be regenerated to prevent potential session fixation attacks. See the commit note here: https://github.com/fuel/auth/commit/263c9d0d7544ea135ea7a24b77d537e88fa9e1bd#commitcomment-562844

**Comment by WanWizard** [comment]
By default the session ID is rotated every 300 seconds by the Session class, so there is mitigation against session fixation in place.

But you are right, in general it is good practice to rotate the session ID whenever the security level changes.
