### ISSUE TITLE
Add dynamic salt to user's password hash?

### ISSUE THREAD

**Issue by arbme** [fuel/auth#33]
Should a dynamic salt be used with the static salt in the config to generate the users hashed password, so its harder to be cracked if the database was every hacked as each user has a different salt.

\fuel\packages\auth\classes\auth\login\driver.php

```
    /**
 * Default password hash method
 *
 * @param   string
 * @return  string
 */
public function hash_password($password, $user_salt)
{
    return base64_encode($this->hasher()->pbkdf2($password, \Config::get('auth.salt').$user_salt, 10000, 32));
}
```

You could save the user's dynamic salt its own column in users table or add it to the password column and use substr() to split the salt from the hashed password and then pass it to hash_password($password, $user_salt). The login() method would also need minor edits to change the sql and checking the hashes are correct.

Im not sure how to do it for other storage drivers as I have not used them.

Hope this helps.

Thanks

**Comment by jschreuder** [comment]
The PBKDF2 hashing is powerfull enough not to need this, we're using the same settings as iOS4 if wikipedia is to be believed. If you really want it you can implement it in a driver of your own, but from a security POV it makes little practical difference.

**Comment by kenjis** [comment]
> from a security POV it makes little practical difference.

It has much difference if password hashes are stolen.

OWASP Password Storage Cheat Sheet says:

>  Generate a unique salt upon creation of each stored credential (not just per user or system wide); 
> https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Use_a_cryptographically_strong_credential-specific_salt

**Comment by WanWizard** [comment]
It's pretty pointless. Any scenario that allows for the theft of the password hashes will also expose all per-user salts, since they are in the same table. The code is open source, so the hacker knows the algorithm for applying the salt and hashing the password, which renders the per-user salt completely usesless.
