### ISSUE TITLE
get_user_array() error without additional_fields in config

### ISSUE THREAD

**Issue by axelitus** [fuel/auth#34]
I'm working on an Ldap Auth Driver and I haven't set a `$config['additional_fields']` entry in the config array.

When I try to use the `get_user_array()` function (inherited from `auth.php`) I get the following error:

```
Notice!
ErrorException [ Notice ]: Undefined index: additional_fields
PKGPATH/auth/classes/auth/login/driver.php @ line 110:
```

Wouldn't it be better to use:

```
$additional_fields = array_merge(\Arr::get($this->config, 'additional_fields', array()), $additional_fields);
```

instead of:

```
$additional_fields = array_merge($this->config['additional_fields'], $additional_fields);
```

for people that don't have a `$config['additional_fields']` in their drivers?

**Comment by WanWizard** [comment]
Send a pull request...

**Comment by axelitus** [comment]
Done, sorry, yesterday I had no time to do a Pull request (#35)...

It seems that this does no affect the driver base class but just prevents the error merging an empty array to the method's additional_fields parameter...
