### ISSUE TITLE
verify_multiple_logins causes BadMethodCallException

### ISSUE THREAD

**Issue by kenjis** [fuel/auth#37]
BadMethodCallException [ Error ]: Invalid method: Auth\Auth::get_screen_name
PKGPATH/auth/classes/auth.php @ line 352

How to reproduce:
1. oil generate admin ...
2. config/auth.php:
   'verify_multiple_logins' => true,
3. login

**Comment by jschreuder** [comment]
That is by design, when multiple drivers are allowed there's no way of determining which driver the method call was intended for and thus the static call cannot work and you have to call it on the Login driver specificly using `Auth::instance('name')`
