### ISSUE TITLE
Throw separate Exceptions in Auth_Login_SimpleAuth

### ISSUE THREAD

**Issue by stalmok** [fuel/auth#38]
Use case: http://fuelphp.com/forums/topics/view/8962

**Comment by WanWizard** [comment]
Checked the code: there are 10 different exceptions being thrown, I don't think 10 different exceptions would be the solution. I'll number them instead, so you can use `$e->getCode()` to check what the error is.

**Comment by stalmok** [comment]
I agree, in my case this will allow to get translation string by code dumber and I don't need to check all exceptions one by one. Thanks.
