### ISSUE TITLE
\Auth::forge($config) - $config is ignored

### ISSUE THREAD

**Issue by lukearmstrong** [fuel/auth#40]
I am working on a site where I plan on using one Auth driver for the front-end, and one driver for the CMS (this is in a separate package/module). Neither are using `SimpleAuth`.

I was setting up migrations, as both Auth drivers save users in the db, and create a user, and found that the migrations for one package were failing because they were using the Auth driver from another package, and the tables didn't exist yet so it threw an error.

``` php
<?php

\Auth::forge('MyPackage\MyDriver'):
```

If I have an auth driver defined in an `config/auth.php` anywhere, it will use that, otherwise it will use `SimpleAuth`. It will completely ignore `MyPackage\MyDriver` because the `_init()` function finds a driver from `Config` and then forges `Auth` again.

To work around this I have had to do this.

``` php
<?php

\Config::load('auth', true);
\Config::set('auth.driver', 'MyPackage\MyDriver');
\Auth::forge();
```

**Comment by lukearmstrong** [comment]
This line is the problem...
https://github.com/fuel/auth/blob/1.3/develop/classes/auth.php#L68

**Comment by lukearmstrong** [comment]
Actually, my proposed work around above doesn't work.

``` php
<?php

\Config::load('auth', true);
\Config::set('auth.driver', 'MyPackage\MyDriver');
\Auth::forge();
```

It returns this error:

```
Error: Undefined index: driver in ../fuel/packages/auth/classes/auth.php on 88
```

You have to specify something in forge, otherwise it fails. It can be anything as it is ignored

``` php
<?php

\Config::load('auth', true);
\Config::set('auth.driver', 'MyPackage\MyDriver');
\Auth::forge('MyPackage\MyDriver');
```

**Comment by WanWizard** [comment]
This shouldn't be a problem, as you can forge multiple drivers without a problem.

If you don't want Auth to autoload the default driver, don't define one in the config.

**Comment by WanWizard** [comment]
I have looked into this issue again.

_init() pre-loads one or more drivers as configured in the config file. If at least one is loaded, the first one is designated the default driver and is accessable through the static methods.

When you call Auth::forge(), you don't pass it a class name, you pass it a driver name, or a namespace and a driver name. With this name, a login driver is forged. In this example, it will look for the \MyPackage\Auth_Login_MyDriver class. If loaded the instance will be added and returned. This does not interfere in any way with the instances already loaded, providing you've got your classnames ok, and your driver names are unique.

I can't find any flaw in this.
