### ISSUE TITLE
Auth::logout can miss verified drivers

### ISSUE THREAD

**Issue by iturgeon** [fuel/auth#43]
I ran into this problem in an extensive unit test on my app:

This test will fail:

``` php
public function setUp()
{
    \Auth::instance()->create_user('dave', 'dave', 'dave@mail.edu', 1);
}

public function tearDown()
{
    \Auth::instance()->delete_user('dave');
}

public function test_auth_logout()
{
    // log in the new user
    // NOTE: this never updates \Auth::$_verified
    $this->assertTrue(\Auth::instance()->login('dave', 'dave'));

    // log out the new user
    // NOTE: this resets \Auth::$_verified but leaves an instance of the auth driver verified
    $this->assertNull(\Auth::logout());

    // Get the screen name of the supposedly logged out user
    // This will revive the the verified auth driver missed in the logout loop
    $this->assertFalse(\Auth::instance()->get_screen_name());
}
```

1) Test_Api_V1::test_auth_logout
Failed asserting that 'dave' is false.
### Proposed fix to Auth.php

On logout, methodically logout all known drivers, instead of just the known verified drivers.

``` php
/**
 * Logs out all current logged in drivers
 */
public static function logout()
{
    foreach (static::$_instances as $i)
    {
        $i = $i instanceof Auth_Login_Driver ? $i : static::instance($i);
        $i->logout();
    }

    static::$_verified = array();
}
```
### Possible other approaches:

Driver login methods could pass through Auth (instead of Auth::instance()->login).  Then Auth would be aware of the login situation.

Another approach may be for each driver to register it's verified status with Auth with something like Auth::register_verified_driver($me)

I can put together a pull request once you validate I'm not going in the wrong direction.

**Comment by WanWizard** [comment]
The verified registration takes place in `check()`, only a call to `login()` is not enough to get the driver in verified state.

**Comment by iturgeon** [comment]
This problem also affects check()

It's never a problem, unless the `Auth::logout()` is called prior to `Auth::check()`, which is what I was running into.

``` php
public function test_auth_logout()
{
    // log in the new user
    // NOTE: this never updates \Auth::$_verified
    $this->assertTrue(\Auth::instance()->login('dave', 'dave'));

    // log out the new user
    // NOTE: this resets \Auth::$_verified but leaves an instance of the auth driver verified
    $this->assertNull(\Auth::logout());

    // Fails "Failed asserting that true is false."
    $this->assertFalse(\Auth::check());
}
```

I guess it wasn't clear to me that I'd need to call check() after login() to register the validated driver with Auth.

Is this a functionality or documentation issue?

**Comment by WanWizard** [comment]
I haven't written Auth, so I have to check what the intention was. But I think that because you would have a check() call in your code, executed on every request, and you do a redirect after login, this has never been an issue.

I think all that is needed is that login() should call

``` php
\Auth::_register_verified($this);
```

after the login has been successful.

**Comment by WanWizard** [comment]
That merge fixed this issue.
