### ISSUE TITLE
get_user_array bug

### ISSUE THREAD

**Issue by helloer** [fuel/auth#5]
get_user_array gives old user data when i use update_user. Example:

<pre>
first_name = "bla"..
now i update user..

Auth::instance()->update_user(array(
"first_name" => "blabla"), "helloer");

now i want get user_data
$user_data = Auth::instance()->get_user_array();
echo $user_data['first_name'];
Result : bla
</pre>

**Comment by jschreuder** [comment]
Comment for when I get round to fixing this: update_user() should update the db row kept with the driver as well, currently the DB is updated but the internal copy of the user isn't.
