### ISSUE TITLE
1.6/development get exception

### ISSUE THREAD

**Issue by takyam-git** [fuel/auth#50]
I update core and packages version to 1.6/development.

When use SimpleAuth, got error.

`ErrorException [ Error ]: Class 'Auth_Login_Simpleauth' not found`

In commit (67fabb63ee2bb2ad881daf4e836326bbcd2ca45b) , change `ucfirst` to `\Str::ucwords`.

It was returned `Auth_Login_Simpleauth` instead of  `Auth_Login_SimpleAuth`.

I roll back to 92a45afbb670b96066a9594e0af2d029c20b63e8 for auth package. It move correctly.

**Comment by WanWizard** [comment]
This is basically caused due to the "illegal" classnames that are used, it should be "Auth_Login_Simpleauth" according to Fuel standards. I've just fixed this.

Note that if you have extended the Auth classes, you'll have to update the classnames there too.

**Comment by takyam-git** [comment]
@WanWizard thanks!!
