### ISSUE TITLE
SimpleAuth inserts password hash into short database field

### ISSUE THREAD

**Issue by jeteon** [fuel/auth#58]
If a database is created with a char(40) field for the password and then a user is created, the hashed password will be inserted into the field and truncated to fit. 

When the user then attempts to log on, SimpleAuth checks the new hash against the stored (truncated) hash and finds a mismatch, always. 

I know it seems like a silly problem but it took me a rather long time to debug this in my setup. Is it possible to have some kind of warning when this occurs?

**Comment by kenjis** [comment]
It' MySQL's behavior.

You can change the SQL mode to `STRICT_ALL_TABLES`.
http://dev.mysql.com/doc/refman/5.5/en/server-sql-mode.html

**Comment by jeteon** [comment]
I see. Managed to reproduce that behaviour and only got a warning on the insert. I guess it'd be a nice to have to catch these.
