### ISSUE TITLE
Opauth strategy with Google (redirect_uri)

### ISSUE THREAD

**Issue by mgabrielro** [fuel/auth#59]
It will be a good idea to be documented, that in case of using the Auth_Opauth class, with Google, the user must register on the Google Apis Console, the redirect_uri as : http://example.com/login/session/google/oauth2callback.

Where : 
login - is the controller
session - is the method which takes care of the \Auth_Opauth instantiation
google - is the provider name (passed to the session method)

Is different from Facebook (where you don't have to set a redirect_uri), 
or Twitter / Linkedin where the redirect_uri would be like this : 
http://example.com/login/callback/

**Comment by WanWizard** [comment]
Done.
