### ISSUE TITLE
Model\Auth_Role issue with Fieldset

### ISSUE THREAD

**Issue by jhuriez** [fuel/auth#60]
Hi, i want to show the fieldset with the model Auth_Role, but i have an error with __toString()

My code 

``` php
 $form = \Fieldset::forge('roleform', array('form_attributes' => array('class' => 'form-horizontal')));

        $form->add_model('Auth\\Model\\Auth_Role');
        echo $form;
        die();
```

The error message : 

```
Fatal error: Method Fuel\Core\Fieldset::__toString() must not throw an exception in ...
```

The bug line is the "echo $form;"

**Comment by jhuriez** [comment]
Ok i've found my issue, it's because i have not create a lang file "auth_model_*" for my language ...

**Comment by WanWizard** [comment]
That is odd, it should default to 'en' if the current language could not be found. Or did you change the fallback language too?

edit: just verified, and yes, that must have been the case. 

Always make sure the 'language_fallback' in your config is set to something that exists, usually 'en'.
