### ISSUE TITLE
Problem with auth_check()?

### ISSUE THREAD

**Issue by pwrhead** [fuel/auth#7]
Noticed a strange issue during some testing. Let's have this code for example:

```
if (Auth::instance()->login('test', 'test'))
{
    // valid user
    Response::redirect('users');
}
else
{
    // invalid user
    Response::redirect('users/login');
}

if (Auth::check()) print "User exists!";
```

If we remove out else { } part, and user test/test doesn't exists, this code will always print "User exists!". 
I can't figure out where problem is exactly, maybe somewhere in Auth::check code.

**Comment by pwrhead** [comment]
Looks like this is a duplicate of issue #2, but bug still exists (your fix doesn't have effects).

**Comment by jschreuder** [comment]
This has been solved in the develop branch and will be in the next release.
