### ISSUE TITLE
Bug with logout when remember_me()

### ISSUE THREAD

**Issue by KirillArtemenko** [fuel/auth#75]
When enabled remember_me logout don't working!

Fixing is add to end of logout method this line:
\Auth::dont_remember_me();

Thx! You are the best!

**Comment by KirillArtemenko** [comment]
Sorry on my production project this solution not help :(
User can not logout, with this config (when enable checkbox and Auth::remember_me() is called ):

return array(
    'guest_login' => true,
    'multiple_logins' => true,
    'username_post_key' => 'auth.login',
    'password_post_key' => 'auth.password',
    'remember_me' =>
    array(
        'enabled' => true,
        'cookie_name' => 'rmcookie',
        'expiration' => 2592000,
    ),
);

**Comment by KirillArtemenko** [comment]
User Auto-login on this line (auth/login/simpleauth.php line 103)
return $this->force_login($user_id);

**Comment by KirillArtemenko** [comment]
I found problem! This happens only when set cookie domain with dot in beginning. But i think add Auth::dont_remember_me() method to Auth::logout() still need.

**Comment by WanWizard** [comment]
The "Remember me" function uses a custom Session instance. There was a bug in Session related to deleting the session cookie if you use a custom domain config which was fixed here: https://github.com/fuel/core/commit/904a0e308057f23c6263e4be588816b4b4490095#diff-3b5e41dfbf537c22ca7bf63f2cc522a5R70, just to late to make it for the 1.7.1 maintenance release. 

I think this will fix your problem too.

**Comment by KirillArtemenko** [comment]
Completely! :)

**Comment by amityadav4a** [comment]
Auth::dont_remember_me(); not working on localhost(wampserver).

I can see rmcookie in browser after calling Auth::dont_remember_me();
