### ISSUE TITLE
Ormacl has_access bug

### ISSUE THREAD

**Issue by yuriymyrosh** [fuel/auth#77]
Ormacl has_access method gives an error:

Fuel\Core\FuelException [ Error ]:
Primary key on model Auth\Model\Auth_Rolepermission cannot be changed.

It is because of mistake in /fuel/packages/auth/classes/auth/acl/ormacl.php file on line 165

if ($rolepermission->role_id == $role->id and $rolepermission->perms_id = $permission->id)

There must be == instead of =

**Comment by WanWizard** [comment]
Fixed https://github.com/fuel/auth/commit/174abf48f8cf025b2d3420e5e12c489411010d62
