### ISSUE TITLE
ORMAuth not properly migrating on MariaDB10

### ISSUE THREAD

**Issue by Dracon23** [fuel/auth#79]
Using ORMAuth on MariaDB 10.0.7 throws https://gist.github.com/Dracon23/e87618539de3c808dc3b as an error.

key is a reserved word in MariaDB, causing the query to go bonkers. Exchanging key for u_key should fix this.

**Comment by WanWizard** [comment]
DBUtil::create_table() calls DB::quote_identifier() when generating the SQL, which means for MySQL (and MariaDB) it should enclose identifiers in backticks.

Is your database configuration (app/config/db.php) ok, i.e. does it contain

```
'identifier'   => '`',
```

in your database definition? If not, identifiers will not be escaped, causing this problem.

**Comment by Dracon23** [comment]
It does.

I've tried running the produced query through command line, it wouldn't 
work either.

MariaDB chokes on the "key" field for whatever reason, quoted or not. Or 
my system is broken in a way I cannot see.

Changing out the value in question for "u_key" and making the 
adjustments in the code did fix things.
Am 05.02.2014 23:31, schrieb Harro Verton:

**Comment by WanWizard** [comment]
Your gist clearly shows the generated SQL for the create table, and it doesn't have backticks around the column names, that's why I ask.

I am running MariaDB on my laptop (on Fedora 20), and it works fine when I do this:

```
create table test ( `key` int(11) NOT NULL )
```

**Comment by Dracon23** [comment]
Hm, I'll triple check, but I'm sure, that I did have the identifier setting set...

**Comment by WanWizard** [comment]
What happens if you run my test 'create table'?

**Comment by Dracon23** [comment]
Tried running the command on my dev machine, it comes up with a syntax error.
However, I just threw up a fresh vm with the exact same setup, and it works ootb without alterations there...

Gonna reinstall the system...

**Comment by WanWizard** [comment]
Lol, these things happen.  Good to hear you've got it sorted.
