### ISSUE TITLE
Migrate old 1.x up to 1.8 develop

### ISSUE THREAD

**Issue by huglester** [fuel/auth#84]
Hello everyone,

been trying to track out changes to has_access() but did not figure out what exacly has broken.

Auth_Acl_Simpleacl has `has_access()` method,
inside it, first thing we have, is:
`$group = \Auth::group($entity[0]);`

for  for me, $group is false for guest, but I have enabled guest login, and since I get false,
I am not passing this if:

``` php
if ( ! is_array($condition) || empty($group) || ! is_callable(array($group, 'get_roles')))
        {
            return false;
        }
```

`Auth::guest_login()` also returns true. 
So basicly guest is not allowed anywhere anymore...

By default buest is assigned id 0. I have this in config: 

``` php

return array(
    'table_name' => 'users',
    'login_hash_salt' => 'some_salt',
    'groups' => array(
        0       => array('name' => 'Guests', 'roles' => array('guest')),
...
```

Any idea what am I missing?

Thanks

**Comment by WanWizard** [comment]
It might be initialisation. In `Auth_Login_Simpleauth`, the `logout()` method will check the guest setting, and if enabled, it assigns the dummy guest user to `$this->user`.  But as far as I can see, `$this->user` starts out as `null`, but it doesn't seem to be initialised with the guest user on load.

Could you check if that is the case, and if so, if adding this will solve it:

```
protected function __construct(Array $config)
{
    $this->user = \Config::get('simpleauth.guest_login', true) ? static::$guest_login : false;
    parent::__construct($config);
}
```

**Comment by huglester** [comment]
Hello,

have been playing around to see what is going on, etc :)
it seems it was my error, I have renamed classes, etc but found out that one parameter must also be replaced:

``` php
class Auth_Login_Simpleauth extends \Auth\Auth_Login_Simpleauth {

    protected $config = array(
        'drivers' => array('group' => array('Simplegroup')),
        'additional_fields' => array('user_id', 'username', 'vip')
    );
```

I had: SimpleGroup :(

hope everything else will work just fine

**Comment by WanWizard** [comment]
So this can be closed?

**Comment by huglester** [comment]
@WanWizard I think yes, I have checked all the situations and old logins seems to be working nicely! just that small caseSenSItivitY issue. 

Thanks for fast help!
