### ISSUE TITLE
Facebook not always returning email

### ISSUE THREAD

**Issue by andymoreno** [fuel/auth#91]
It seems Facebook doesn't always return an email address when authenticating. This will make Auth_Login_Ormauth->create_user() bail out, in my case it would be a-ok to just make up the 'default' facebook email by stringing together the username with @facebook.com. At the very least I don't want it to bail out completely... Is there any way to prevent the bail-out from happening, or if the provider is specifically Facebook then make up the email on the fly?

Thank you.

**Comment by WanWizard** [comment]
This seems more like a Facebook API and/or an Opauth thing. 

Instead of working around this, it might be more beneficial to figure out why Facebook "sometimes" doesn't return the email address. The workaround might do it for you, but not for anyone requiring a valid email address.

**Comment by andymoreno** [comment]
One answer about the Facebook 'sometimes': http://stackoverflow.com/a/20766201/836358

So, let me re-phrase; how would I override Auth_Login_Ormauth->create_user()?

**Comment by WanWizard** [comment]
Auth is aliased to Global, so you can override Auth classes the same way you can override Core classes:

create `Auth_Login_Ormauth` in `./app/classes/auth/login/ormauth.php`, have that extend `\Auth\Auth_Login_Ormauth`, and add it to the autoloader using the add_classes() method in your app bootstrap (there is already a commented-out example in there).

**Comment by andymoreno** [comment]
Works perfectly for me, thank you!
