### ISSUE TITLE
session.php (config) error

### ISSUE THREAD

**Issue by codingjungle** [fuel/auth#93]
if you auto-generate the session configuration with oil, it will have this error in it:

'header_header_name' => 'Session-Id',

when the sessions/driver.php looks for:

$this->config['http_header_name']

this will throw an undefined index error upon initializing the session class (which in development mode throws a wrench in the works :))

**Comment by WanWizard** [comment]
This is a core issue, not an auth issue. 

And it has been fixed here: https://github.com/fuel/core/commit/51226cc615f48e22e30ccfe1665497f3f0c32f43 8 months ago.

What in oil generates a session config? (if that is wrong, it should be reported on the fuel/oil repo).
